name: 'publiccode.yml parser and validation Action'
description: |
    This action can be integrated in your CI configuration 
    to have a constant validation of your publiccode.yml
branding:
  icon: 'align-right'
  color: 'green'
inputs:
  publiccode:
    description: 'publiccode.yml path'
    required: true
    default: 'publiccode.yml'
  comment-on-pr:
    description: 'publiccode.yml path'
    required: false
    default: "false"
outputs:
  validation:
    description: 'publiccode.yml validation output'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.publiccode }}
    - ${{ inputs.comment-on-pr }}
